# ==========================================
# 1. Backend Deployment (FastAPI Microservice)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kavidevops03/swiftbite-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URL
              value: "mongodb://mongodb:27017"
            - name: DATABASE_NAME
              value: "swiftbite"
            - name: JWT_SECRET
              value: "swiftbite-secret-key-12345"

---
# ==========================================
# 2. Backend Service (ClusterIP Internal)
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  sessionAffinity: ClientIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend
