apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiftbite-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kavibalan1904/swiftbite-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URL
              value: "mongodb://mongodb:27017"
            - name: DATABASE_NAME
              value: "swiftbite"
            - name: JWT_SECRET
              value: "swiftbite-secret-key-12345"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend
